### ISSUE TITLE
21. Merge Two Sorted Lists

### ISSUE THREAD

**Issue by BeokBeok** [StudyFork/AlgorithmStudy#126]
- level: Easy
- tags: Linked List, Recursion
- [문제 링크](https://leetcode.com/problems/merge-two-sorted-lists/)

**Comment by ddaeyeonkim** [comment]
전에도 풀었던 문제였네요ㅋㅋ

**Comment by BeokBeok** [comment]
> 전에도 풀었던 문제였네요ㅋㅋ

제가 풀다가 틀렸어서 낸건데, 전에 풀었던 문제였군요 ㅋㅋㅋ
