### ISSUE TITLE
563. Binary Tree Tilt

### ISSUE THREAD

**Issue by ddaeyeonkim** [StudyFork/AlgorithmStudy#135]
- level: Easy
- tags: Tree, Depth-First Search, Binary Tree
- [문제 링크](https://leetcode.com/problems/binary-tree-tilt/)

**Comment by BeokBeok** [comment]
싫어요가 더 많은 문제네요 ㅋㅋㅋ

**Comment by ddaeyeonkim** [comment]
> 싫어요가 더 많은 문제네요 ㅋㅋㅋ

왜 싫어요가 많은지 알거 같네요ㅜㅠㅋㅋㅋ
